name: Build and Deploy Node.js app

on:
  push:
    branches: [main,node]

jobs:
  build-docker:
    name: Build and deploy Node projects
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME_NODE}}
          password: ${{secrets.DOCKERHUB_TOKEN_NODE}}
          
      - name: Listar contenido del directorio front
        run: ls

      - name: Build and push Node.js Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./front  # Ajusta la ruta al directorio de tu aplicación Node.js
          dockerfile: Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME_NODE}}/nodeappbot:latest

  deploy:
    name: Deploy to DonWeb NodeApp
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - name: install ssh pass
        run: sudo apt-get install -y sshpass

      - name: SSH INTO DON WEB SERVER - DEPLOY NODEBOT
        run: |
          sshpass -p ${{ secrets.VPS_PASSWORD_ANTONIO }} ssh -p 5355 -o StrictHostKeyChecking=no ${{ secrets.VPS_USER_ANTONIO }}@${{ secrets.VPS_HOST_ANTONIO }} << EOF
          docker rm -f nodebot  
          docker login -u ${{ secrets.DOCKERHUB_USERNAME_NODE }} -p ${{ secrets.DOCKERHUB_TOKEN_NODE }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME_NODE }}/nodeappbot2024:latest
          docker run -d \
          --restart always \
          --name nodebot \
          -e "PHONE_NUMBER=${{secrets.PHONE_NUMBER}}" \
          -e USE_PAIRING_CODE=true \
          -e "JWT_SECRET=${{secrets.JWT_SECRET}}" \
          -e "SLACK_URL=${{secrets.SLACK_URL}}" \
          -e "EMAIL_TO=${{secrets.EMAIL_TO}}" \
          -e "RESEND_API_KEY=${{secrets.RESEND_API_KEY}}" \
          -e "WEB_SERVICE_URL=${{secrets.WEB_SERVICE_URL}}" \
          -e "API_URL=${{secrets.API_URL}}" \
          -p 3000:3000 \
          ${{secrets.DOCKERHUB_USERNAME_NODE}}/nodeappbot:latest
          EOF
#          docker run -v /home/cashier/zephyr/bot_sessions:/app/bot_sessions -d \
#          --restart always \
#          --name nodeappbot \
#          -e "PHONE_NUMBER=${{secrets.PHONE_NUMBER}}" \
#          -e USE_PAIRING_CODE=true \
#          -e "JWT_SECRET=${{secrets.JWT_SECRET}}" \
#          -e "SLACK_URL=${{secrets.SLACK_URL}}" \
#          -e "EMAIL_TO=${{secrets.EMAIL_TO}}" \
#          -e "RESEND_API_KEY=${{secrets.RESEND_API_KEY}}" \
#          -e "WEB_SERVICE_URL=${{secrets.WEB_SERVICE_URL}}" \
#          -e "API_URL=${{secrets.API_URL}}" \
#          -p 3000:3000 \
#          ${{secrets.DOCKERHUB_USERNAME}}/nodeappbot:latest
#
#docker run -p 3323:3306 --name mysql_trucking --network spring-mysql-network --restart always -v /root/backend/app:/var/lib/mysql -e  MYSQL_DATABASE=db_trucking -e MYSQL_ROOT_PASSWORD=trucking2023  -d  mysql:8.0.33
