name: Build and Deploy Spring boot app

on:
  push:
    branches: [dev,main]

jobs:
  build-docker:
    name: Build and deploy spring project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn -f back/pom.xml clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Copy .env file
        run: cp back/.env back/

      - name: Build and push docker hub
        uses: docker/build-push-action@v5
        with:
          context: ./back
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT }}:latest


  deploy:
    name: Deploy to DonWeb
    needs: build-docker
    runs-on: self-hosted #ubuntu-latest

    steps:

      - name: Docker Instance Stop and remove
        run: docker rm -f devbot

      - name: Docker pull image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devbot:latest

      - name: Docker run image
        run: |
          docker run -d \
          --restart always \
          --name devbot \
          -p9698:9698 \
          ${{ secrets.DOCKERHUB_USERNAME }}/devbot:latest
#docker run -p 3323:3306 --name mysql_trucking --network spring-mysql-network --restart always -v /root/backend/app:/var/lib/mysql -e  MYSQL_DATABASE=db_trucking -e MYSQL_ROOT_PASSWORD=trucking2023  -d  mysql:8.0.33